
# Développement
FROM node:23-slim AS development
ARG ANGULAR_PORT=4200 # Port par défaut pour Angular
ENV PORT=$ANGULAR_PORT
ENV NODE_ENV=development
WORKDIR /src/app
COPY package*.json ./
RUN npm install -g @angular/cli && npm install
COPY . .
CMD ["sh", "-c", "ng serve --host 0.0.0.0 --port ${ANGULAR_PORT} --disable-host-check"]

# Production
FROM node:23-slim AS production
ARG ANGULAR_PORT=80
ENV PORT=$ANGULAR_PORT
ENV NODE_ENV=production
WORKDIR /src/app
COPY package*.json ./
COPY package-lock.json ./
RUN npm install --omit=dev --no-audit --fund=false --legacy-peer-deps
COPY . .
RUN npm run build
CMD ["sh", "-c", "npx http-server dist -p ${ANGULAR_PORT}"]