# Développement
FROM node:23-slim AS development

WORKDIR /Back-end
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.dev .env
EXPOSE 5000
CMD ["npm", "run", "dev"]

# Production
FROM node:23-slim AS production

WORKDIR /Back-end
COPY package*.json ./
RUN npm ci --only=production
COPY . .
COPY .env.production .env
EXPOSE 5000
CMD ["npm", "start"]