sonar.projectKey=eco-fit-backend
sonar.projectName=EcoFit Backend
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts
sonar.tests=tests
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
